version: "0.2"
dictionaries:
  - ruby
  - english
  - project-words
dictionaryDefinitions:
  - name: project-words
    path: ./project-words.txt
    addWords: true
ignorePaths:
  - agent/node_modules/*
  - facesign-service/node_modules/*
  - entropy-service/node_modules/*
  - facetec-sdk/*
  - aws-nitro-kernel/*
  - facesign-service/env.ts
  - entropy-service/env.ts
